hacbs-release/app-interface-deployments

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

* Add changes from hacbs-release/internal-services-resources#50

feat(HACBS-1715): migrate fixes

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

feat(HACBS-1715): correct overwrite_from_index* params

feat(HACBS-1715): correct overwrite_from_index* params 

---

internal-services/manager/manager.yaml

* once again, experiencing OOMKilled/CrashLoopBackOff on prod

feat(HACBS-2205): increase mem for prod

---

internal-services/catalog/file-updates-pipeline.yaml
internal-services/catalog/file-updates-process-file-updates-task.yaml

This PR adds the parameter `upstream_repo` to the file-updates pipeline and also to the `task-process-file-updates`.

feat(HACBS-2590): adds parameter upstream_repo to file-updates

---

internal-services/catalog/file-updates-pipeline.yaml
internal-services/catalog/file-updates-process-file-updates-task.yaml

Relevant PR for Release Pipeline: https://github.com/redhat-appstudio/release-service-bundles/pull/194

feat(HACBS-2228): use application in title of MR

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/publish-index-image-task.yaml

- remove deprecated release-base-image usage

fix(RHTAPBUGS-709): use correct release-utils base image

---

internal-services/manager/manager.yaml

roll back internal services

---

internal-services/manager/manager.yaml

- 313e4e05ae306295f242e9cd0e1cf7a39415839e

revert to older version

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml
internal-services/catalog/publish-index-image-task.yaml

This PR add the hotfix parameter to the `iib` pipeline and task to enable building hotfixes.
It also refactor the genericResult content to be saved in json format.

feat(RHTAPREL-382): add hotfix param to iib build

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

This PR forces the default to publish and sign to false.

fix: setting default to publish and sign to false

---

internal-services/config/signing/production/hacbs-signing-pipeline-config-redhatbeta2.yaml
internal-services/config/signing/staging/hacbs-signing-pipeline-config-redhatbeta2.yaml

- add new configMap for beta2
- remove old generic named configMap

feat(RHTAPREL-182): new beta2 key

---

internal-services/catalog/create-advisory-pipeline.yaml
internal-services/catalog/create-advisory-task.yaml
internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

Promotes main branch to stable. Contains commits for the following ticket:
- RHTAPREL-858
- RHTAPREL-815
- RHTAPREL-793

chore(noticket): promote main to stable

---

internal-services/manager/staging/manager-staging-p01.yaml

- allows us to have multiple controllers

enable override of election leader Id

---

internal-services/manager/production/manager-prod-rh01.yaml
internal-services/manager/production/manager-staging-p01.yaml
internal-services/manager/staging/manager-staging-p01.yaml
internal-services/manager/staging/manager-staging-rh01.yaml

- new tag: quay.io/redhat-appstudio/internal-services:enable-leader-election-override

fix: update pullspec for temp image

---

internal-services/catalog/check-embargoed-cves-pipeline.yaml
internal-services/catalog/check-embargoed-cves-task.yaml

Add both a tekton pipeline and task for checking if any CVEs are embargoed.

feat(RHTAPREL-663): add embargo check pipeline

---

internal-services/manager/production/manager-prod-p01.yaml

- prod deployment should the prod-p01 remote config

chore: support prod-p01

---

internal-services/catalog/check-embargoed-cves-pipeline.yaml
internal-services/catalog/check-embargoed-cves-task.yaml
internal-services/manager/production/manager-prod-p01.yaml
internal-services/manager/production/manager-prod-rh01.yaml
internal-services/manager/staging/manager-staging-p01.yaml
internal-services/manager/staging/manager-staging-rh01.yaml

- feat(RHTAPREL-663): add embargo check pipeline
- chore: support prod-p01
- chore: update tag for controller

chore: sync stable based on main

---

internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-openshifthosted.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatbeta2.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatrelease2.yaml

- correct SSL_CERT_SECRET_NAME value in staging configMaps

fix(KFLUXBUGS-1255): allow staging signing configmaps in prod

---

internal-services/manager/production/manager-prod-p02.yaml

chore: add new prod-p02 cluster

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

this commit adds `set -x` to increase the verbosity of the script

fix: increasing verbosity

---

internal-services/catalog/pulp-push-disk-images-pipeline.yaml
internal-services/catalog/pulp-push-disk-images-task.yaml

This task adds a pipeline and task to the catalog to push disk images via pulp.

feat(RELEASE-971): add task and pipeline to push disk images

---

internal-services/catalog/pulp-push-disk-images-pipeline.yaml
internal-services/catalog/pulp-push-disk-images-task.yaml

feat(RELEASE-1108): push disk images to cgw

---

internal-services/catalog/pulp-push-disk-images-task.yaml

fix: correct loading of json

---

internal-services/catalog/pulp-push-disk-images-pipeline.yaml
internal-services/catalog/pulp-push-disk-images-task.yaml

- new wrapper developer_portal_wrapper
- uses konflux-ci/release-service-utils#218

fix(RELEASE-1108): use new wrapper

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- fixed executable bit on developer-portal-wrapper

fix(RELEASE-1108): update release-service-utils image

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- entire function was being sent to stderr instead of command execution.
- update image to get fixes for stdout logging

fix(RELEASE-1108): fix stderr and update image

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- Ensure metadata present before processing component

fix(RELEASE-1108): add validation of component data

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- fix to correct issue with shortUrl in dev-portal wrapper

fix: update release-service-utils image

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- place version key under .component[].staged.version

fix(RHELAI-1140): correct location for version

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

Promote the iib pipeline and task from main to stable so that IIB errors are better exposed to users.

chore(KFLUXBUGS-1278): promote main to stable

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

this PR promotes RELEASE-1102 and KFLUXBUGS-1614 to stable

feat: promoting to stable

---

internal-services/manager/manager.yaml
internal-services/manager/production/manager-prod-p01.yaml
internal-services/manager/production/manager-prod-p02.yaml

this PR fixes the minum cpu requests set for the controller.

fix: cpu min should not be less than 50m

---

internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatbeta2.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatrelease2.yaml

- make sure staging configmaps in prod use correct keys

fix: update signing stage configs

---

internal-services/catalog/file-updates-pipeline.yaml
internal-services/catalog/file-updates-process-file-updates-task.yaml

- allow file-updates-secret to be configurable

feat(RELEASE-1283): file-updates secret update

---

internal-services/catalog/file-updates-process-file-updates-task.yaml

- change reference to RHTAP to Konflux

feat(RELEASE-1283): file-updates naming

---

internal-services/catalog/file-updates-pipeline.yaml
internal-services/catalog/file-updates-process-file-updates-task.yaml

Reverts hacbs-release/app-interface-deployments#233

Revert "chore(RELEASE-1040): remove file-updates"

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- pickup release-service-utils/334

fix(KFLUXSPRT-794): update release utils image

---

internal-services/manager/production/manager-prod-ocp-p01.yaml

- new manager deployment for konfux instance prod-ocp-p01

add new deployment for prod-ocp-p01

---

internal-services/manager/staging/manager-staging-p01.yaml
internal-services/manager/staging/manager-staging-rh01.yaml

The new manager has support for InternalRequest.Spec.Pipeline so we can use resolvers.

chore(RELEASE-1327): bump staging manager images

---

internal-services/manager/production/manager-prod-rh02.yaml

This commit adds a new deployment for the new internal-services prod rh02 cluster.

feat(RELEASE-1506): add new deployment

---

internal-services/rbac/service_account.yaml

- add secret for trusted artifacts to release-service-account SA
- relates to https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/141226

feat(RELEASE-1564): add trusted artifacts creds

---

internal-services/config/cronjob/cleanup-internal-requests-pipelineruns.yaml

the script should include only finished pipelineruns

fix: script should include only finished plr

---

internal-services/config/cronjob/cleanup-internal-requests-pipelineruns.yaml

the script should include only finished pipelineruns.

fix: script should only include finished plr

---

internal-services/manager/production/manager-prod-rh03.yaml

This commit add a new deployment for the production cluster rh03.

feat(RELEASE-1768): add rh03 manager
