internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

Fix the output saved in `buildState` result to be always a regular string. For some reason the `-cr` param is making openshift understand the result as an object.
https://console-openshift-console.apps.appsres03ue1.5nvu.p1.openshiftapps.com/k8s/ns/stonesoup-int-srvc/tekton.dev~v1beta1~PipelineRun/internalrequest-cph6h

fix: remove jq -cr param to keep result as string

---

internal-services/config/networkpolicy/production/network_policy.yaml
internal-services/config/networkpolicy/staging/network_policy.yaml

The following commit adds an Egress Network Policy to the internal-service app-interface cluster,
only allowing traffic to listed `ipBlock` and blocking the rest of the traffic from the cluster for better security

feat(HACBS-2107): Add Network Policy to internl-service controller

---

internal-services/config/networkpolicy/production/network_policy.yaml
internal-services/config/networkpolicy/staging/network_policy.yaml

This commit will add more IP CIDR to the network policy
to allow better coverage and reliability. And also removes 
Hypershift target from the prod Network policy.

add more IP CIDR to network policy

---

internal-services/config/networkpolicy/production/network_policy.yaml

This commit allow egress to all. In order for change to be applied in prod we need an MR in the [app-interface](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/stonesoup/internal-services/cicd/stonesoup-internal-services.appsrep05ue1.yaml#L75l) repo for updating `ref`.

allow egress in prod Netowrk Policy

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml
internal-services/catalog/publish-index-image-pipeline.yaml
internal-services/catalog/publish-index-image-task.yaml

HACBS-2207: Production IIB pipeline only overwrites fromImage and copies to
targetImage when opted-in.
- changes task `t-add-fbc-fragment-to-index-image` to check if FBC index
is optIn instead of using `overwriteFromIndex` parameter
- removes `overwriteFromIndex` parameter
- updates `release-base-image` version
- adds `misc` result
- adds `publish-index-image` pipeline
- adds `task-publish-index-image` task

feat(HACBS-2207): Production IIB pipeline only overwrites fromImage and copies to targetImage when opted-in

---

internal-services/catalog/publish-index-image-pipeline.yaml

Fix: The parameter `publishingCredentials` for the `publish-index-image` Pipeline should have no default set
Ref: https://github.com/redhat-appstudio/release-service-bundles/pull/133

fix: removes default value for `publishingCredentials`

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

FBC pre-GA release strategy requires different credentials, so we should be able to set them.

fix: adjusts to fit the new pre-ga release strategy

---

internal-services/catalog/file-updates-pipeline.yaml
internal-services/catalog/file-updates-process-file-updates-task.yaml

feat(HACBS-2226): create a task to clone a repo and update files given fileUpdates for repo.

feat(HACBS-2226): create a task to clone a repo and update files given fileUpdates for repo.

---

.github/workflows/lint.yaml

All the yaml files except for the catalog are automatically
updated from the internal-services repo (and they are auto generated
by a Makefile there). So every time the files are updated,
they violate yamllint rules. It's better to exclude them
altogether and only run yamllint on the catalog subdir
(which is updated manually).
Issue found by David.

fix: only run yamllint on catalog and not the rest

---

.github/gitlint/contrib_format_conventional_commits.py

Updates gitlint to support "revert" as a prefix

feat(HACBS-2506): add revert prefix support

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

This PR moves the shell line break added inside the jq query expression to the right place.

fix: move shell line break outside jq expression

---

internal-services/catalog/file-updates-process-file-updates-task.yaml

fix: the task should rebase the branch before create the MR
This PR changes the task `process-file-updates` to rebase
the current branch with the upstream repo and given revision
before creating the MR

fix: rebase before MR

---

internal-services/catalog/file-updates-process-file-updates-task.yaml

- remove the prefix 'chore' from MR title
- most teams in app-interface do not use conventional commits

fix(HACBS-2228): remove chore in MR title

---

internal-services/config/signing/production/hacbs-signing-pipeline-config-openshifthosted.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-redhatrelease2.yaml
internal-services/config/signing/staging/hacbs-signing-pipeline-config-openshifthosted.yaml
internal-services/config/signing/staging/hacbs-signing-pipeline-config-redhatrelease2.yaml

- hacbs-signing-pipeline-config-openshifthosted
- hacbs-signing-pipeline-config-redhatrelease2
Contents based on https://docs.engineering.redhat.com/display/PRODSEC/Signing+Server+User+Guide#SigningServerUserGuide-3.SigningKeysInUse
These configMaps will be specified in the release pipeline.

feat(RHTAPREL-622): add new configmaps for signing

---

internal-services/catalog/create-advisory-task.yaml

This commit changes the create-advisory task to push the advisories to a staging directory. The advisory name is also just a uuidgen now, as a gitlab ci pipeline will do that part instead. The logic that was present to help determine the advisory name is removed.
In addition, the error and trap handling in the task was updated

refactor(RHTAPREL-643): update create-advisory task logic

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

This PR fix the value assignment that should reset the array when assigning the new value.
When `uniq` return a single value, the array should contain a single item, not multiple as 
it is happening when the fragment has multiple images, causing it to always enter a condition
that is not the one wanted (ie. having multiple images with different `fbc_opt_in` values).

fix: reset array while setting the new value

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

- set parameters accordingly when stagedIndex = true.
- we want to force opt_in to false and ensure no images are overwritten or published
Related to https://github.com/redhat-appstudio/release-service-catalog/pull/305

fix(RHTAPBUGS-1019): add support for staged index use case

---

internal-services/catalog/create-advisory-pipeline.yaml
internal-services/catalog/create-advisory-task.yaml

advisory.spec in the data.json is becoming releaseNotes. The template is not changing, however. So, this commit updates the create-advisory-task to pass advisory.spec to the template instead of just advisory to make up for that .spec field no longer existing in the data.json.

refactor(RHTAPREL-773): pass advisory.spec in advisory task

---

internal-services/catalog/create-advisory-task.yaml

The new base image includes releaseNotes.product_name and releaseNotes.product_version in the advisory template.

feat(RHTAPREL-818): bump create-advisory-task base image

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

This PR fix the wrong error output when the build times out. 
If the IIB build fails for any reason, the correct error should
be displayed, not the skopeo one.

fix(RHTAPREL-858): error parsing image name "docker:// null"

---

internal-services/catalog/create-advisory-task.yaml

The advisory template now expects a new variable
to set metadata.ship_date in the advisory.
Depends on: https://github.com/redhat-appstudio/release-service-utils/pull/129

feat(RHTAPREL-799): add ship date to advisory

---

internal-services/catalog/create-advisory-task.yaml

The updated image contains an updated advisory template which will populate the metadata.updated_date field when creating an advisory.
See this related PR:
https://github.com/redhat-appstudio/release-service-utils/pull/130

feat(RHTAPREL-799): update utils image in create-advisory task

---

internal-services/catalog/create-advisory-task.yaml

The create-advisory-task secrets were moved on the cluster and the
ERRATA_API should be a secret so the stage and prod tasks don't differ.

feat(RHTAPREL-878): update create-advisory-task secrets

---

internal-services/manager/production/manager-prod-rh01.yaml
internal-services/manager/production/manager-staging-p01.yaml
internal-services/manager/staging/manager-staging-p01.yaml
internal-services/manager/staging/manager-staging-rh01.yaml

- due to outage with chains, it was not possible to create a release earlier.
- this updated the manager files with the latest release image pullspec

chore: use latest released image

---

internal-services/catalog/create-advisory-task.yaml

In order to support string values with single quotes in the advisory_json parameter of the create-advisory-task, the parameter is declared as an env variable for the task script instead of using the parameter directly.

fix(RHTAPREL-891): declare param as env var in advisory task

---

internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-openshifthosted.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatbeta2.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatrelease2.yaml

- in production, we can now enable requesting signatures from RADAS stage is the event a push to registry.stage.redhat.io is performed.
- use data.sign.configMapName: hacbs-signing-pipeline-config-staging-\<keyName\>
- images signed with these configMaps with be signed with the redhate2etesting key
- we must eventually add some logic in the CI tests of konflux-release-data to verify that the config maps for staging are only used for pushes to redhat-pending

fix(KFLUXBUGS-1255): allow staging signing configmaps in prod

---

internal-services/catalog/create-advisory-task.yaml

The create advisory task is throwing errors writing to / so cd to /tmp at the beginning of the task.

fix: create-advisory-task operates in /tmp dir

---

internal-services/catalog/create-advisory-task.yaml

- in cases where you have a non-privileged container. we should to try to not overwrite /etc/krb5.conf

fix(KFLUXBUGS-1291): does not overwrite krb5.conf

---

internal-services/catalog/create-advisory-pipeline.yaml
internal-services/catalog/create-advisory-task.yaml

- remove the need to use the repo value from ReleaseServiceConfig
- use the repo field from the Advisory Secret

fix(RELEASE-928): switch to using secret for repo

---

internal-services/catalog/create-advisory-pipeline.yaml
internal-services/catalog/create-advisory-task.yaml

- pipeline and task for create-advisory was correct to no longer use a hard-coded secret name. It is now a parameter.
- that parameter is already sent in the release pipeline and passed in the InternalRequest.

fix(RELEASE-928): remove hardcoded secret name

---

internal-services/rbac/role.yaml
internal-services/rbac/role_binding.yaml

renaming "manager-role" to  "internal-services-manager-role" and  "internal-service-role-binding"
to create clarity about what this role and binding do.

chore: renaming manager role

---

internal-services/catalog/publish-index-image-task.yaml

Promoting to stable branch
This commit fixes the check for the url, adding the AUTH_PARAM 
only when the sourceIndex is not the registry-proxy.

fix(RELEASE-948): hotfix feature not working properly

---

internal-services/catalog/check-embargoed-cves-task.yaml
internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

* Update KRB5_CONFIG to use temporary storage to avoid permission errors after cluster migration

fix(RELEASE-926): update KRB5_CONFIG

---

internal-services/manager/manager.yaml

This commit updates the quay image reference for the internal-services manager to the new location in the konflux-ci quay org.

refactor(RELEASE-977): migrate internal-services quay org

---

internal-services/config/internal-services/internal-services/config/internal-services/production/internal-services-config.yaml
internal-services/config/internal-services/internal-services/config/internal-services/staging/internal-services-config.yaml

This commit adds the InternalServiceConfigs config definitions
so they can be fetched and applied in the prod and stage appsre
ocp clusters.
Signed-off-by: Leandro Mendes lmendes@redhat.com

fix(KFLUXBUGS-1282): (stable) InternalServiceConfigs are not stored in git

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

this commit increases the verbosity of the `iib-add-fbc-fragment-to-index-image-task`
by adding a `set -x` to it.

fix: increase verbosity

---

.github/workflows/lint.yaml

This updates the linting workflow by adding Checkton. Checkton will review the code for linting errors.
Changes:
* Added a step to the workflow to run Checkton on PR.
* Configured Checkton to upload the SARIF report.

feat(RELEASE-951): integrate Checkton for linting

---

internal-services/rbac/service_account.yaml

Add a new service account to use for our internal service pipelineruns instead of using the default pipeline SA that tekton provides.
The benefit is that we can control this one and link it to what we need.

feat(RELEASE-1046): add SA for executing pipelineruns

---

internal-services/catalog/pulp-push-disk-images-pipeline.yaml
internal-services/catalog/pulp-push-disk-images-task.yaml
internal-services/crds/appstudio.redhat.com_internalrequests.yaml
internal-services/manager/manager.yaml
internal-services/manager/production/manager-prod-p01.yaml
internal-services/manager/production/manager-prod-p02.yaml
internal-services/manager/production/manager-prod-rh01.yaml
internal-services/manager/staging/manager-staging-p01.yaml
internal-services/rbac/service_account.yaml

This bumps all the resources to be in sync for what is in the main branch for passing service accounts to pipelineRuns and adding the pulp pipeline and task.

chore: bump main to stable for RELEASE-1045

---

internal-services/catalog/check-embargoed-cves-task.yaml
internal-services/catalog/create-advisory-task.yaml
internal-services/catalog/file-updates-process-file-updates-task.yaml
internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/publish-index-image-task.yaml

This commit addresses [CVE-2024-3727](https://github.com/advisories/GHSA-6wvf-f2vw-3425) by updating references and bumping images.
Changes include:
- Updating all references from quay.io/hacbs-release/release-service-utils
to the latest available tag at quay.io/konflux-ci/release-service-utils.
- Bumping quay.io/konflux-ci/release-service-utils
to the latest available tag.
Signed-off-by: Sean Conroy <sconroy@redhat.com>

feat(RELEASE-1006): update references to `release-service-utils`

---

internal-services/catalog/pulp-push-disk-images-task.yaml

This commit modifies the pulp-push-to-cdn-task to manually create the ~/.docker/config.json file instead of relying on tekton to do it via volume mounts as changing tekton config flags will make tekton no longer add the volume mount. So, let's not depend on it.

fix: manually create docker config for pulp

---

internal-services/catalog/pulp-push-disk-images-task.yaml

The task should not fail if the directory already exists.

fix: add -p to mkdir in pulp push task

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- developer_portal_wrapper was not spelled correctly.

fix(RELEASE-1108): fix typo in executable name

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- since process_component is run in a thread, we cannot use global var to collect DESTINATIONS
- scrape the destinations from the staged JSON

fix(RELEASE-1108): cannot use global var in thread

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- capture the error message when validating.

fix(RELEASE-1108): improve error messaging

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

The tekton result was still over the max, so cut the log size further.

fix: decrease iib log size

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

This commit exposes the iib error if one occurred in the iib operation and bubbles it up to the pipelineRun as a result. It also changes the iib-add-fbc-fragment-to-index-image task to never fail.

fix(KFLUXBUGS-1278): make iib errors available to users

---

internal-services/catalog/pulp-push-disk-images-pipeline.yaml

The disk images for RHEL AI are very big and
we repeatedly saw timeouts. We will make it
customizable here:
https://issues.redhat.com/browse/RELEASE-1143
But for now, let's increase the value.

fix: increase timeout for push-disk-images IR

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- files uploaded by push-disk pipeline are not associated to a version in the customer portal.
- this change uses the component's version specified in the RPA when creating the metadata during the push operation
See https://redhat-internal.slack.com/archives/C01B8PCHP1V/p1725042411227469?thread_ts=1725029056.832849&cid=C01B8PCHP1V

fix(RHELAI-1140): files uploaded not associated

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- resulting value from version string is over-quoted

fix(RHELAI-1140): correct version

---

.github/workflows/lint.yaml

Originally, our goal was to write a special
script to parse the sarif file and print a nice summary.
But since then, Adam improved the output of the checkton action, so that it has all we need (including link to wiki for each issue), so we can just use that.
This the same as was done in the main catalog repo here: https://github.com/konflux-ci/release-service-catalog/pull/536
I tested it here by modifying a task and then it ran as expected (with 1 issue): https://github.com/hacbs-release/app-interface-deployments/actions/runs/10666209886/job/29561166377?pr=182

refactor(RELEASE-1024): update checkton version and allow it to fail

---

internal-services/catalog/check-embargoed-cves-task.yaml
internal-services/catalog/create-advisory-task.yaml
internal-services/catalog/file-updates-process-file-updates-task.yaml
internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/publish-index-image-task.yaml

This commit addresses CVE-2024-3727 by updating
references and bumping images.
Changes include:
- Updating all references from quay.io/hacbs-release/release-service-utils to the latest available tag at quay.io/konflux-ci/release-service-utils.
- Bumping quay.io/konflux-ci/release-service-utils to the latest available tag.

feat(RELEASE-1006):Bump update references to release-service-utils 

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

this commit removes the passing of the binaryImage parameter to IIB, so it can auto resolve it.

fix(KFLUXBUGS-1614): fbc pipeline should stop passing binaryImage to iib

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

this commit removes references of unused or unecessary parameters in FBC Release Pipeline and tasks,
namely: iibServiceConfigSecret, iibServiceAccountSecret and iibOverwriteFromIndexCredential.

feat(RELEASE-1102): remove unused data.fbc parameters from fbc

---

internal-services/catalog/sign-image-pipeline.yaml

This pipeline yaml is a copy of the pipeline we currently use: hacbs-signing-pipeline
The goal here is to enable retry in the request-signature task, see here:
https://issues.redhat.com/browse/RELEASE-1194
For that, I needed to update the task reference. But that broke the task because the current version of the task does not have the signature_data result.
In order to test this, I am deploying this modified pipeline under a different name.
Once this is tested, we may actually switch to using this going forward - we can evaluate this afterwards.

feat: add sign-image pipeline

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

fix: missing removing two more occurences of iibServiceConfigSecret

fix: missing removing two more occurences of iibServiceConfigSecret

---

internal-services/catalog/check-embargoed-cves-task.yaml
internal-services/catalog/create-advisory-task.yaml
internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

Recently, we had issues when doing kinit, it would say:
kinit: Generic error (see e-text) while
getting initial credentials
It was suggested to us to enable
kerberos trace logging so that next time
we have more details to report.
This is the same as https://github.com/hacbs-release/app-interface-deployments/pull/190 but for prod

fix: enable more logging for kinit

---

internal-services/catalog/pulp-push-disk-images-pipeline.yaml

This commit bumps the task timeout of the pulp-push-disk-images tekton task in the pulp-push-disk-images pipeline to 24 hours. The hope is that this is high enough for the RPA timeouts to control the timeout instead of the task timeout.

chore(RELEASE-1143): bump pulp tekton task timeout to 24h

---

internal-services/catalog/publish-index-image-task.yaml

the PR fixes the bug caused by when an empty `$AUTH_PARAM` is passed the quotes are preserved, causing skopeo to complain on the unknown parameter.

fix: empty variable should not keep quotes

---

internal-services/catalog/sign-image-pipeline.yaml

The old bundle reference was deprecated in Tekton 1.15 and removed in 1.16 and app-sre just deployed 1.16 which broke signing in Konflux. Updating to bundle resolver format should fix it.
Note that this pipeline definition is still not really used, we use the hacbs-signing-pipeline from a different repo, but this is a copy we have and it's useful
for testing.

fix(RELEASE-1271): use bundle resolver in signing pipeline

---

internal-services/catalog/sign-image-pipeline.yaml

The lines were too long and yamllint didn't like it. I tried to split them using `>-` but that didn't work - it added an extra space in between. This should work.
I tested this using a test yaml:
```
---
something:
longstring: "my long\
string"
```
And then reading it with `yq` and it was able to render it correctly:
```
---
something:
longstring: "my longstring"
```

fix: spliting of long string

---

internal-services/catalog/sign-image-pipeline.yaml

The correct name of the resolver is actually bundles, not bundle.
Note: This pipeline isn't really used, it's a copy of the hacbs-signing-pipeline. It's used for testing only.
See:
https://github.com/konflux-ci/release-service-catalog/pull/655

fix(RELEASE-1271): correct name for bundles resolver

---

internal-services/catalog/create-advisory-task.yaml

This commit modifies the create-advisory-task to validate the generated advisory.yaml against the advisory schema before pushing it to the repo.

feat(RELEASE-1223): validate created advisory against schema

---

.github/CODEOWNERS

This will automatically add everybody on the team
as reviewers for new pull requests (unless
they are created as a draft).

feat: add CODEOWNERS file to auto assign reviewers

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- reverting part of 48b581f9f01c61243f60e42bc3c58cca26fc6a85
- causing "could not find rhelai-1_DOT_2-for-rhel-9... (no ./ prefix)."

fix: partially revert disk-image task linting fix

---

internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatbeta2.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatrelease2.yaml

- since we are using stage services for releasing stage content, we need to ensure that we are using a key that can sign on stage RADAS.

fix: revert to using redhate2etesting key

---

internal-services/catalog/file-updates-pipeline.yaml
internal-services/catalog/file-updates-process-file-updates-task.yaml

* allow file-updates-secret to be configurable
* change reference to RHTAP to Konflux

feat(RELEASE-1283): file-updates updates

---

internal-services/catalog/create-advisory-pipeline.yaml
internal-services/catalog/create-advisory-task.yaml

This commit changes the create-advisory task and pipeline to accept a parameter for the errata secret instead of hardcoding it. This allows us to differentiate stage and prod.

fix(KFLUXBUGS-1896): do not hardcode errata secret name for advisories

---

internal-services/config/signing/staging/hacbs-signing-pipeline-config-openshifthosted.yaml
internal-services/config/signing/staging/hacbs-signing-pipeline-config-redhatbeta2.yaml
internal-services/config/signing/staging/hacbs-signing-pipeline-config-redhatrelease2.yaml

We would like to start using prod RADAS for all signing (see RELEASE-1191 ). As a first step, we changed the secrets that are deployed in staging app sre cluster:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/125757
Previouly, we would have two secrets in the stage cluster
- prod and nonprod. But both would contain the nonprod client cert. With this change, the prod contains prod cert and nonprod contains nonprod cert.
When it got merged, we suddenly started using prod client cert for all signing in stage cluster (e2e) and we thought it might work, but apparently it doesn't and broke e2e.
So instead of reverting that app interface change, let's just change the configMaps to use the nonprod secret.
That way we can keep testing how/if we can use the prod certs to use …

fix: use staging secret for signing pipelines used in stage

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

This PR modifies the task add-fbc-fragment-to-index-image idempotent by checking IIB endpoint for builds for the current fbc_fragment, considering only prod builds and builds complete or in progress.
In addition, it also fixes shellcheck lint errors.

feat(RELEASE-1242): make add-fbc-contribution idempotent

---

internal-services/config/internal-services/production/internal-services-config.yaml

this PR re-enables the debug in InternalServicesConfig. A following up PR will add a cronjob to keep only the last day of internalrequests.

chore: re-enabling debug

---

internal-services/config/signing/production/hacbs-signing-pipeline-config-openshifthosted.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-redhatbeta2.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-redhatrelease2.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-openshifthosted.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatbeta2.yaml
internal-services/config/signing/production/hacbs-signing-pipeline-config-staging-redhatrelease2.yaml
internal-services/config/signing/staging/hacbs-signing-pipeline-config-openshifthosted.yaml
internal-services/config/signing/staging/hacbs-signing-pipeline-config-redhatbeta2.yaml
internal-services/config/signing/staging/hacbs-signing-pipeline-config-redhatrelease2.yaml

This commit modifies the signing configMaps to have pyxis and umb specific ssl keys. They are just copied for now so nothing breaks. The existing ones will be removed at a later date so that only the PYXIS_ and UMB_ ssl keys remain.

refactor(RELEASE-1191): add pyxis/umb specific keys to configmaps

---

internal-services/catalog/pulp-push-disk-images-task.yaml

- Change name of CGW_TOKEN to CGW_PASSWORD
- This is actually a token, no pw, but the pubtools library expects this environment variable name
- Relevant PR to pubtools: https://github.com/release-engineering/pubtools-content-gateway/pull/38
- Accompanies this open PR: 
- https://github.com/konflux-ci/release-service-utils/pull/334

fix(KFLUXSPRT-794): pass content-gateway token as env var

---

internal-services/catalog/simple-signing-pipeline.yaml

Temporary addition to the stable branch until it is in release-service-catalog production.

chore: add simple-signing-pipeline

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml

this PR fixes the lint issues in the taskiib-add-fbc-fragment-to-index-image-task. In
addition, adjusts the fbc_opt_in code tobe more clear.

fix(RELEASE-1099): lint issue on iib-add-fbc-fragment-to-index-image

---

internal-services/config/cronjob/cleanup-internal-requests-pipelineruns.yaml

this PR adds a new cronjob to the stonesoup-int-srvc namespace to clean up the last day pipelineruns left of finished internal-requests.

chore: add cronjob to clean up pipelineruns

---

internal-services/config/cronjob/cleanup-internal-requests-pipelineruns.yaml

this PR adds the new cronjob to create pipelineruns

chore: add cronjob to delete pipelineruns - staging

---

internal-services/catalog/pulp-push-disk-images-task.yaml

The script called in the pulp-push-disk-images task started failing because `packaging` was not explicitly installed in the utils image. Now that it is, the utils image is bumped to fix the error.

fix: update utils image in push-disk-images task

---

internal-services/catalog/iib-add-fbc-fragment-to-index-image-task.yaml
internal-services/catalog/iib-pipeline.yaml

this PR make the iib-add-fbc-fragment to require a new IIB build when the resumed catalog is older than the upstream one to ensure the catalog integrity.

fix(RELEASE-1338): new build for old catalog index

---

internal-services/manager/production/manager-prod-ocp-p01.yaml
internal-services/manager/production/manager-prod-p01.yaml
internal-services/manager/production/manager-prod-p02.yaml
internal-services/manager/production/manager-prod-rh01.yaml
internal-services/manager/production/manager-prod-rh02.yaml
internal-services/manager/staging/manager-staging-p01.yaml
internal-services/manager/staging/manager-staging-rh01.yaml

This commit rolls back PR 303, which removed
InternalRequest.Spec.Request in the operator in prod/stable.

revert: rollback prod operator

---

internal-services/config/cronjob/cleanup-internal-requests-pipelineruns.yaml

this PR changes the internal request clean up
cronjob to run hourly, and deleting pipelineruns
older than 12 hours.

chore(RELEASE-1673): change cronjob periodicity (stable)

---

.github/renovate.json
.gitlint
internal-services/config/cronjob/cleanup-internal-requests-pipelineruns.yaml

chore(deps): enable renovate to bump utils image
* Add Renovate JSON config to bump utils image weekly on Wednesday at 14:00 UTC
* Pin image references to digests
* Updates .gitlint to ignore Renovate bot PRs.
Related Tickets: KONFLUX-7804 & KONFLUX-7648
Tested here: https://github.com/seanconroy2021/test-renovate/pull/23

chore(KONFLUX-7648): enable renovate to bump utils image

---

.github/renovate.json
.github/scripts/promote-image-digest.sh
.github/workflows/promote-utils-digest.yaml
internal-services/config/cronjob/cleanup-internal-requests-pipelineruns.yaml

* Add a script to promote the release-service-utils digest from `main` to `stable`, with a workflow that runs every Wednesday at 14:00 UTC to open/update the PR.
* Switch Renovate from schedule to cron because the previous way didn’t allow enough time for the job to run. Now using CRON runs at 15:00 UTC, leaving a one-hour window after the promotion workflow.
Example PR: https://github.com/seanconroy2021/app-interface-deployments/pull/21

feat(RELEASE-1828): add weekly digest promotion

---

.github/workflows/pr-assigner.yaml

add pr reviewer auto-assignment workflow to the main branch. WF taken from RSC.

chore: add pr reviewer auto-assignment WF to main

---

internal-services/manager/staging/manager-staging-rh01.yaml

We will use the common cluster instead of app-sre going forward.

chore(RELEASE-1862): scale down stage manager rh01 to 0 replicas

---

internal-services/manager/production/manager-prod-ocp-p01.yaml
internal-services/manager/production/manager-prod-osp-p01.yaml
internal-services/manager/production/manager-prod-p02.yaml
internal-services/manager/production/manager-prod-rh01.yaml
internal-services/manager/production/manager-prod-rh02.yaml
internal-services/manager/production/manager-prod-rh03.yaml
internal-services/manager/production/manager-prod-rhel-p01.yaml

This commit scales down the remaining production managers to 0 replicas as they will be replaced by ones on the new common cluster.

chore(RELEASE-1863): scale down all prod managers
